version: '3'
services:
  postgres:
    image: postgres:9.6.2-alpine
    network_mode: cloudbuild
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_DB: bobby_test
